name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hallee/eslint-action@master
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
